#!/bin/bash

# Added (A), Copied (C), Deleted (D), Renamed (R)
update_required=$(yadm diff --name-only --diff-filter=ACDR HEAD~ HEAD)

if [ -n "$update_required" ]; then
    make -C $HOME frece-quick-edit
fi
