#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio           0.60
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config automatic_scheme      longest_side
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
