#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4

bspc config border_width          3
bspc config focused_border_color  "#abb2bf"
bspc config presel_feedback_color "#c678dd"
bspc config window_gap            5

bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        true
bspc config automatic_scheme      longest_side
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

# Rules
bspc rule -r '*'
bspc rule -a cmus state=floating sticky=true \
    rectangle=1070x640+0+0 center=true border=off
bspc rule -a scratchpad state=floating sticky=true \
    rectangle=1070x640+0+0 center=true
bspc rule -a *:*:Emulator layer=below state=pseudo_tiled
