theme = "onedark"

[keys.normal]
# ";" = "command_mode"
# ":" = "collapse_selection"
"backspace" = "file_picker"
"A-x" = ["extend_to_line_bounds", "trim_selections"]
"g" = { "l" = "extend_to_line_end", "h" = "extend_to_line_start" }
"ret" = ":write"
"g" = { "l" = "extend_to_line_end", "h" = "extend_to_line_start" , "e"="goto_file_end" }

[keys.select]
# till eof in select mode, to beginning of last line in normal mode
"g" = { "e" = "goto_file_end" }

[keys.insert]
"j" = { "k" = "normal_mode" }

[editor]
line-number = "relative"
scrolloff = 3
idle-timeout = 200
# cursor-shape = { "insert" = "bar", "select" = "underline" }
