theme = "onedark"

[keys.normal]
# ";" = "command_mode"
# ":" = "collapse_selection"
"backspace" = "file_picker"
"A-x" = ["extend_to_line_bounds", "trim_selections"]
"g" = { "l" = "extend_to_line_end", "h" = "extend_to_line_start" }
"ret" = ":write"
"g" = { "l" = "extend_to_line_end", "h" = "extend_to_line_start" , "e"="goto_file_end" }

[keys.select]
# till eof in select mode, to beginning of last line in normal mode
"g" = { "e" = "goto_file_end" }

[keys.insert]
"j" = { "k" = "normal_mode" }
"C-t" = "indent"
"C-d" = "unindent"

[editor]
line-number = "relative"
scrolloff = 3
idle-timeout = 50
rulers = [80]
mouse = false
completion-trigger-len = 1
auto-completion = true
cursorline = true
indent-guides.render = true
# diff-symbols = ["▍", "▍", "▁", "▔"]


[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.whitespace.render]
newline = "all"

[editor.lsp]
display-messages = true

# [editor.status-line]
# left = ["file-name", "file-encoding", "file-type" ]