[language-server]
# ltex-ls = { command = "ltex-ls" }
typst-lsp = { command = "typst-lsp" }

[[language]]
name = "python"
auto-format = true

[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "^typ(st)?$"
file-types = ["typ"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
# language-servers = [ "typst-lsp" ]
roots = []

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'$' = '$'

[[grammar]]
name = "typst"
source = { git = "https://github.com/frozolotl/tree-sitter-typst", rev = "50915c5fefd6d6d2f48b3e6da7136cb0138b160a" }

# [[language]]
# name = "markdown"
# language-servers = [ "ltex-ls", "marksman" ]

[[language]]
name = "chey"
scope = "source.chey"
injection-regex = "chey"
file-types = ["chey", "todo.txt"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
roots = []

[[grammar]]
name = "chey"
source = { path = "/home/gokul/Projects/chey/tree-sitter" }
