[language-server.beancount-language-server]
command = "beancount-language-server"
args = ["--stdio"]
config = { journal_file = "/home/gokul/.hledger.journal" } 

[language-server.typst-lsp]
command = "typst-lsp"
# config = { experimentalFormatterMode = "on" } 

[language-server.emmet-lsp]
command = "emmet-language-server"
args = ["--stdio"]

[language-server.ruff]
command = "ruff-lsp"
config = { settings = { run = "onSave" } }

[language-server.anakinls]
command = "anakinls"

[language-server.pyright-debug]
command = "/home/gokul/Projects/pyright/packages/pyright/langserver.index.js"
args = ["--stdio"]
config = {}

[language-server.word]
command = "simple-completion-language-server"

[[language]]
name = "python"
auto-format = true
language-servers = ["ruff", "pyright"]
# language-servers = ["ruff", "pyright-debug"]
# language-servers = ["pyright-debug"]

[[language]]
name = "php"
auto-format = true

[[language]]
name = "typescript"
auto-format = true
indent = { tab-width = 4, unit = "    " }

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'$' = '$'

[[language]]
name = "typst"
auto-format = false
# language-servers = ["typst-lsp", "word"]
language-servers = ["word"]
formatter = { command = "typstfmt", args = ["--output", "-"]}


# [[language]]
# name = "markdown"
# language-servers = [ "ltex-ls", "marksman" ]

[[language]]
name = "chey"
scope = "source.chey"
injection-regex = "chey"
file-types = ["chey", "todo.txt"]
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
roots = []

[[grammar]]
name = "chey"
source = { path = "/home/gokul/Projects/chey/tree-sitter" }

[[language]]
name = "beancount"
language-servers = [ "beancount-language-server" ]

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "html"
language-servers = ["vscode-html-language-server", "emmet-lsp"]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "emmet-lsp" ]
